#! /bin/sh

set -e

srcdir="$(dirname "$0")"
test -z "$srcdir" && srcdir=.

cd "$srcdir"

clone_repo_commit() {
    rm -rf $2
    if test -d "$2/.git"; then
        git -C "$2" reset --hard
        git -C "$2" clean -fd
        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
            rm -rf "$2"
        fi
    else
        if test -d "$2"; then
            echo "error: '$2' is not a Git repository" 1>&2
            exit 1
        fi
    fi
    if ! test -d "$2"; then
        git clone $1 "$2"
        if ! git -C "$2" -c advice.detachedHead=false checkout $3; then
            rm -rf "$2"
            exit 1
        fi
    fi
}

rm -f .deps-obtained

clone_repo_commit \
    https://codeberg.org/OSDev/freestnd-c-hdrs-0bsd.git \
    freestnd-c-hdrs \
    5e4e9e70278fe89ea328d359a58aff4f4a94b165

clone_repo_commit \
    https://codeberg.org/OSDev/cc-runtime.git \
    cc-runtime \
    dae79833b57a01b9fd3e359ee31def69f5ae899b

clone_repo_commit \
    https://codeberg.org/Limine/limine-protocol.git \
    limine-protocol \
    fedf97facd1c473ee8720f8dfd5a71d03490d928

clone_repo_commit \
    https://github.com/uACPI/uACPI \
    uACPI \
    c4d70797a54f3a1843a3e26426e9b57c40fbba7b

clone_repo_commit \
    https://github.com/managarm/frigg/ \
    frigg \
    98220ab8f3ac6b1f146c360598a334f7f1fc06e1

touch .deps-obtained

printf "\nDependencies obtained successfully.\n"
