name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: mirror-repository
      uses: yesolutions/mirror-action@v0.7.0
      with:
        REMOTE: "https://codeberg.org/TendingStream73/x64OS"
        GIT_USERNAME: TendingStream73
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
    - uses: ilammy/setup-nasm@v1
    - name: download submodules
      run: git submodule init && git submodule update
    - name: make
      run: make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        # Artifact name
        name: Bootable image
        # A file, directory or wildcard pattern that describes what to upload
        path: image.iso
